/* INCLUSÃO DAS BIBLIOTECAS NECESSÁRIAS PARA O FUNCIONAMENTO E GERENCIAMENTO DO PROJETO*/
#include <Arduino.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

/* INCLUSÃO DAS BIBLIOTECAS NECESSÁRIAS PARA Os MÓDULOS PROJETO */
#include "DHT.h"    // Sensor DHT11

/* DEFINIÇÃO NECESSÁRIAS PARA A EXECUÇÃO DO PROJETO */
#define DHTTYPE DHT11   // Versão utilizada no Projeto

/* HANDLES DAS TAREFAS CRÍTICAS - PRIORIDADE MÁXIMA */


/* HANDLES DAS TAREFAS SECUNDÁRIAS - RPIORIDADE MÉDIA */
TaskHandle_t xReadSensorDHTHandle = NULL;

